## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE

apptype_counts = application_df['APPLICATION_TYPE'].value_counts()
apptype_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [18]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(apptype_counts[apptype_counts < 528].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_count = application_df['CLASSIFICATION'].value_counts()
class_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

class1 = list(class_count[class_count >1].index)

# Replace in dataframe
for cls in class1:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
Other    34273
C1580        1
C1900        1
C1820        1
C6100        1
C1248        1
C2600        1
C1370        1
C5200        1
C4200        1
C2190        1
C1236        1
C2570        1
C3700        1
C2561        1
C2500        1
C1570        1
C1283        1
C2380        1
C1732        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2150        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace  = list(class_count[class_count < 1883].index)

# Replace in dataframe
for cls in classifications_to_replace :
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
Other    34299
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
dummies = pd.get_dummies(application_df)
dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [10]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = dummies['IS_SUCCESSFUL'].values
X = dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [23]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features = len(X_train[0])
hid_nodes_layer1 = 8
hid_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hid_nodes_layer1, input_dim = input_features, activation = "relu"))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hid_nodes_layer2, activation = "relu"))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 8)                 312

 dense_7 (Dense)             (None, 5)                 45

 dense_8 (Dense)             (None, 1)                 6

=================================================================
Total params: 363 (1.42 KB)
Trainable params: 363 (1.42 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [24]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [25]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6194 - accuracy: 0.6817
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5780 - accuracy: 0.7213
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5719 - accuracy: 0.7273
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5701 - accuracy: 0.7260
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5695 - accuracy: 0.7262
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5692 - accuracy: 0.7267
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5686 - accuracy: 0.7261
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7271
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5681 - accuracy: 0.7269
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5682 - accuracy: 0.7267
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5676 - accuracy: 0.7269
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5673 - accuracy: 0.7267
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5671 - accuracy: 0.7269
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5672 - accuracy: 0.7276
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5667 - accuracy: 0.7276
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5667 - accuracy: 0.7273
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5665 - accuracy: 0.7274
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5664 - accuracy: 0.7269
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5662 - accuracy: 0.7266
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5661 - accuracy: 0.7280
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7268
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7271
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5659 - accuracy: 0.7271
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5658 - accuracy: 0.7276
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5657 - accuracy: 0.7271
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5658 - accuracy: 0.7273
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5656 - accuracy: 0.7275
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7271
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5652 - accuracy: 0.7276
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5654 - accuracy: 0.7273
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7279
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5655 - accuracy: 0.7271
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5651 - accuracy: 0.7277
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5651 - accuracy: 0.7282
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5652 - accuracy: 0.7276
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5650 - accuracy: 0.7283
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5651 - accuracy: 0.7282
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7279
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5651 - accuracy: 0.7282
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7279
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7289
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7277
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5647 - accuracy: 0.7284
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7284
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5647 - accuracy: 0.7284
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7283
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7284
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7283
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5645 - accuracy: 0.7290
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7283
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5647 - accuracy: 0.7280
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5642 - accuracy: 0.7289
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5646 - accuracy: 0.7285
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5644 - accuracy: 0.7287
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7287
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7291
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5643 - accuracy: 0.7287
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7288
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5641 - accuracy: 0.7280
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5643 - accuracy: 0.7289
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5640 - accuracy: 0.7292
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7287
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7289
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5643 - accuracy: 0.7284
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5641 - accuracy: 0.7292
Epoch 66/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5641 - accuracy: 0.7279
Epoch 67/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5642 - accuracy: 0.7287
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5641 - accuracy: 0.7285
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7292
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5642 - accuracy: 0.7277
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5637 - accuracy: 0.7285
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5639 - accuracy: 0.7286
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5637 - accuracy: 0.7283
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5639 - accuracy: 0.7290
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5638 - accuracy: 0.7288
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7287
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7290
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5637 - accuracy: 0.7280
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7286
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5636 - accuracy: 0.7291
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5634 - accuracy: 0.7289
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7282
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7288
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7287
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7283
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7289
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5636 - accuracy: 0.7294
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7292
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5634 - accuracy: 0.7287
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5632 - accuracy: 0.7287
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7294
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7285
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7293
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5635 - accuracy: 0.7289
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7292
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5634 - accuracy: 0.7288
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5633 - accuracy: 0.7289
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5633 - accuracy: 0.7288
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5633 - accuracy: 0.7284
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5631 - accuracy: 0.7290

In [35]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5682 - accuracy: 0.7227 - 306ms/epoch - 1ms/step
Loss: 0.5682435035705566, Accuracy: 0.7226822376251221

In [38]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE

nn.save('model.h5')